name: Push already exists kernel to kaggle as new

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ ubuntu-latest, macos-latest ]
        os: [ ubuntu-latest ]
        # python-version: [ '2.7.17', '3.6.10' ]
        python-version: [ '3.6.10' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Kaggle deploy from existing metadata file
      uses: ./
      with:
        kaggle_username: ${{ secrets.kaggle_username }}
        kaggle_key: ${{ secrets.kaggle_key }}
        kaggle_make_new_kernel: true
        kaggle_metadata_path: test/kernel-metadata.json
        kernel_id: joelhanson/github-action-test
        kernel_title: github-action-test
        competition: titanic
    - name: Kaggle deploy as new
      uses: ./
      with:
        kaggle_username: ${{ secrets.kaggle_username }}
        kaggle_key: ${{ secrets.kaggle_key }}
        kaggle_make_new_kernel: true
        # kaggle_metadata_path: kernel-metadata.json
        kernel_id: joelhanson/github-action-test-1
        code_file_path: test/github-action-test-1.ipynb
        language: python
        kernel_type: notebook
        is_private: true
        enable_gpu: false
        enable_internet: false
        competition: titanic
        submit_to_competition: false
        collect_output: true

    - name: Download outputs
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs/outputs.zip
